

services:
  api:
    image: paul423/plantdecor-api:latest
    container_name: plant-api

    ports:
      - "5000:8080"

    # LOAD toàn bộ biến từ file .env
    env_file:
      - .env

    environment:
      - ASPNETCORE_ENVIRONMENT=Production

    depends_on:
      - redis

    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3

    networks:
      - app-network

  redis:
    image: redis:7
    container_name: plant-redis
    command: redis-server --save 60 1
    restart: always

    networks:
      - app-network

networks:
  app-network: