using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlantDecor.API.Responses;
using PlantDecor.BusinessLogicLayer.Exceptions;
using PlantDecor.BusinessLogicLayer.DTOs.Requests;
using PlantDecor.BusinessLogicLayer.DTOs.Responses;
using PlantDecor.BusinessLogicLayer.Interfaces;
using PlantDecor.DataAccessLayer.Helpers;
using System.Security.Claims;

namespace PlantDecor.API.Controllers
{
    /// <summary>
    /// API for AI-powered semantic search and plant recommendations
    /// </summary>
    [Route("api/ai-search")]
    [ApiController]
    public class AISearchController : ControllerBase
    {
        private readonly IAISearchService _aiSearchService;

        public AISearchController(IAISearchService aiSearchService)
        {
            _aiSearchService = aiSearchService;
        }

        /// <summary>
        /// Semantic search for products (plants, combos, materials)
        /// Used by chatbot to answer user queries
        /// </summary>
        /// <param name="request">Search request with query and filters</param>
        /// <returns>List of matching products</returns>
        [HttpPost("search")]
        [AllowAnonymous]
        public async Task<IActionResult> SemanticSearch([FromBody] SemanticSearchRequestDto request)
        {
            var result = await _aiSearchService.SearchPurchasableAsync(
                query: request.Query,
                entityTypes: request.EntityTypes,
                limit: request.Limit ?? 10,
                onlyPurchasable: request.OnlyPurchasable
            );

            return Ok(new ApiResponse<SemanticSearchResponseDto>
            {
                Success = true,
                StatusCode = StatusCodes.Status200OK,
                Message = $"Tìm thấy {result.TotalCount} kết quả",
                Payload = result
            });
        }

        /// <summary>
        /// Get plant recommendations for room design
        /// AI suggests plants based on room description and preferences
        /// </summary>
        /// <param name="request">Room description and preferences</param>
        /// <returns>List of recommended plants</returns>
        [HttpPost("room-recommendation")]
        [AllowAnonymous]
        public async Task<IActionResult> RoomRecommendation([FromBody] RoomRecommendationRequestDto request)
        {
            var result = await _aiSearchService.GetRoomRecommendationsAsync(
                roomDescription: request.RoomDescription,
                fengShuiElement: request.FengShuiElement,
                maxBudget: request.MaxBudget,
                limit: request.Limit ?? 5,
                preferredRooms: request.PreferredRooms,
                petSafe: request.PetSafe,
                childSafe: request.ChildSafe
            );

            return Ok(new ApiResponse<RoomRecommendationResponseDto>
            {
                Success = true,
                StatusCode = StatusCodes.Status200OK,
                Message = $"Đề xuất {result.TotalCount} sản phẩm phù hợp",
                Payload = result
            });
        }

        /// <summary>
        /// Suggest plants based on criteria
        /// </summary>
        /// <param name="query">Query parameters for plant suggestions</param>
        /// <returns>List of suggested plants</returns>
        [HttpGet("suggest-plants")]
        [AllowAnonymous]
        public async Task<IActionResult> SuggestPlants([FromQuery] PlantSuggestionQueryDto query)
        {
            var result = await _aiSearchService.SuggestPlantsAsync(
                description: query.Description,
                fengShuiElement: query.FengShuiElement,
                roomType: query.RoomType,
                onlyPurchasable: query.OnlyPurchasable ?? true,
                limit: query.Limit ?? 10,
                maxBudget: query.MaxBudget
            );

            return Ok(new ApiResponse<List<PlantSuggestionResponseDto>>
            {
                Success = true,
                StatusCode = StatusCodes.Status200OK,
                Message = $"Gợi ý {result.Count} cây phù hợp",
                Payload = result
            });
        }

        /// <summary>
        /// Create a new AI chat session. SessionId is generated by server.
        /// </summary>
        [HttpPost("chatbot/sessions")]
        [Authorize]
        public async Task<IActionResult> CreateChatSession([FromBody] AIChatSessionCreateRequestDto? request)
        {
            var userId = GetCurrentUserId();
            var result = await _aiSearchService.CreateChatSessionAsync(userId, request?.Title);

            return Ok(new ApiResponse<AIChatSessionResponseDto>
            {
                Success = true,
                StatusCode = StatusCodes.Status200OK,
                Message = "Tạo phiên chat thành công",
                Payload = result
            });
        }

        /// <summary>
        /// Get all AI chat sessions of current user (paginated)
        /// </summary>
        [HttpGet("chatbot/sessions")]
        [Authorize]
        public async Task<IActionResult> GetAllSessionByUserId([FromQuery] Pagination pagination)
        {
            var userId = GetCurrentUserId();
            var result = await _aiSearchService.GetAllSessionByUserIdAsync(userId, pagination);

            return Ok(new ApiResponse<PaginatedResult<AIChatSessionListItemResponseDto>>
            {
                Success = true,
                StatusCode = StatusCodes.Status200OK,
                Message = "Get sessions successfully",
                Payload = result
            });
        }

        /// <summary>
        /// Get conversation history by session id (paginated)
        /// </summary>
        [HttpGet("chatbot/sessions/{sessionId:int}/history")]
        [Authorize]
        public async Task<IActionResult> GetConversationHistoryBySessionId(int sessionId, [FromQuery] Pagination pagination)
        {
            var userId = GetCurrentUserId();
            var result = await _aiSearchService.GetConversationHistoryBySessionIdAsync(userId, sessionId, pagination);

            return Ok(new ApiResponse<AIChatConversationHistoryResponseDto>
            {
                Success = true,
                StatusCode = StatusCodes.Status200OK,
                Message = "Get conversation history successfully",
                Payload = result
            });
        }

        /// <summary>
        /// AI chatbot for plant selection, room understanding and plant care consultation
        /// </summary>
        /// <param name="request">Chatbot request</param>
        /// <returns>Chatbot response with answer and optional plant suggestions</returns>
        [HttpPost("chatbot")]
        [Authorize]
        public async Task<IActionResult> Chatbot([FromBody] AIChatbotRequestDto request)
        {
            var userId = GetCurrentUserId();
            var result = await _aiSearchService.ChatbotAsync(request, userId);

            return Ok(new ApiResponse<AIChatbotResponseDto>
            {
                Success = true,
                StatusCode = StatusCodes.Status200OK,
                Message = "Chatbot tư vấn thành công",
                Payload = result
            });
        }

        /// <summary>
        /// Check if a specific product is purchasable
        /// </summary>
        /// <param name="entityType">Type of entity (CommonPlant, PlantInstance, etc.)</param>
        /// <param name="entityId">ID of the entity</param>
        /// <returns>Purchasable status</returns>
        [HttpGet("check-purchasable")]
        [AllowAnonymous]
        public async Task<IActionResult> CheckPurchasable([FromQuery] string entityType, [FromQuery] int entityId)
        {
            var isPurchasable = await _aiSearchService.CheckPurchasableAsync(entityType, entityId);

            return Ok(new ApiResponse<object>
            {
                Success = true,
                StatusCode = StatusCodes.Status200OK,
                Message = isPurchasable ? "Sản phẩm có thể mua" : "Sản phẩm không khả dụng",
                Payload = new { EntityType = entityType, EntityId = entityId, IsPurchasable = isPurchasable }
            });
        }

        private int GetCurrentUserId()
        {
            var userIdClaim = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (string.IsNullOrWhiteSpace(userIdClaim) || !int.TryParse(userIdClaim, out var userId))
            {
                throw new UnauthorizedException("Unable to identify user from token");
            }

            return userId;
        }
    }
}
